name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    description: >
      GitHub token for GitHub API requests.
      Users shouldn't need to set this themselves.
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
